version: '2'
services:
  subgen:
    container_name: subgen
    tty: true
    image: mccloud/subgen
    environment:
       - "WHISPER_MODEL=medium.en"
       - "CONCURRENT_TRANSCRIPTIONS=1"
       - "WHISPER_THREADS=8"
       - "PROCADDEDMEDIA=True"
       - "PROCMEDIAONPLAY=False"
       - "NAMESUBLANG=aa"
       - "SKIPIFINTERNALSUBLANG="
       - "PLEXTOKEN=plextoken"
       - "PLEXSERVER=http://plexserver:32400"
       - "JELLYFINTOKEN=token here"
       - "JELLYFINSERVER=http://jellyfin:8096"
       - "WEBHOOKPORT=9000"
       - "CONCURRENT_TRANSCRIPTIONS=2"
       - "WORD_LEVEL_HIGHLIGHT=False"
       - "DEBUG=True"
       - "USE_PATH_MAPPING=False"
       - "PATH_MAPPING_FROM=/tv"
       - "PATH_MAPPING_TO=/Volumes/TV"
       - "TRANSCRIBE_DEVICE=cuda"
       - "CLEAR_VRAM_ON_COMPLETE=True"
       - "MODEL_PATH=./models"
       - "UPDATE=True"
       - "APPEND=False"
       - "USE_MODEL_PROMPT=False"
       - "CUSTOM_MODEL_PROMPT="
       - "LRC_FOR_AUDIO_FILES=True"
       - "CUSTOM_REGROUP=cm_sl=84_sl=42++++++1"
    volumes:
       - "${TV}:/tv"
       - "${MOVIES}:/movies"
       - "${APPDATA}/subgen/models:/subgen/models"
    ports:
       - "9000:9000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]